spring:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      access-expiration-ms: ${JWT_ACCESS_EXPIRATION}
      refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION}
  config:
    import: "optional:file:application.properties"
  application:
    name: blue-bay
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
stripe:
  publicKey: ${STRIPE_PUBLIC_KEY}
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_KEY}
files:
  propertyImagesPath: ${PROPERTY_IMAGES_PATH}
websiteUrl: ${WEBSITE_URL}